# version: "3.8"

services:
  backend:
    build:
      context: ./google_auth
    container_name: google_auth
    command: gunicorn google_auth.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./google_auth:/google_auth
    env_file:
      - .env
    expose:
      - 8000  # Expose port 8000 to other services in the network
    ports:
      - "8000:8000"  # Map port 8000 on the host to port 8000 in the container

  frontend:
    build:
      context: ./frontend
    container_name: google_auth_frontend
    volumes:
      - ./frontend:/frontend
   
    # environment:
    #   - PORT=5174
    # ports:
    #   - "80:8080"  

  nginx:
    image: nginx:alpine
    container_name: nginx_social_auth

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html  
    ports:
      - "8080:80"  
    depends_on:
      - backend
      - frontend